name: Docker

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: cd backend
      run: cd backend
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: pnadig/sample-backend:latest
    - name: Deploy to GKE
      run: |
        cd backend
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_CLUSTER_REGION }} --project ${{ secrets.GCLOUD_PROJECT_ID }}
        kubectl apply -f k8s/deployment.yaml
      env:
        GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}