name: Docker

on:
  push:
    branches: [ master, GKE-setup ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image

      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: pnadig/sample-backend:latest
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GKE
      run: |
        cd backend
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_CLUSTER_REGION }} --project ${{ secrets.GCLOUD_PROJECT_ID }}
        kubectl apply -f k8s/deployment.yaml